spring:
 data:
   mongodb:
     uri: mongodb://localhost/DistributorsServiceDB
     username: vignesh
     password: root123
     database: DistributorsServiceDB
     port: 27017
     host: localhost
server:
 port: 8080